### ISSUE TITLE
The very first issue

### ISSUE THREAD

**Issue by Dmitry404** [CodeInten/http2-ws#1]
The very first issue, maybe even the most painful, is that I have no clue what to start from. Let's get the ball rolling plz.

**Comment by alex-dukhno** [comment]
I have been thinking for some time about where we could start. I came up with an idea.
We can start simple MVC architecture. 
Whereis:
    - _view_ is a module that works with network connections (we have to take a look at HTTP/2 spec), we can postpone development of this module for now.
    - _model_ is a module that asked for URL's content. IMO URLs are some back-end (Java servlets/JSPs or php scripts or just file on FS. It should be mocked up for now.
    - _controller_ is a module from where we could start server development.

We need to discuss Veiw-Controller and Controller-Model APIs. Should they be separated issues or will discuss them here?

**Comment by Dmitry404** [comment]
<img width="483" alt="screen shot 2016-09-29 at 5 20 15 pm" src="https://cloud.githubusercontent.com/assets/188851/18957800/2221b9b2-8669-11e6-9ad5-786082f6bcbe.png">

This MVC term is a little bit confusing here. As discussed lets assume that:
- `Controller` is a set of objects which represent all stuff we could use for HTTP(HTTP2?) interactions such as Request, Response, etc. 
- `View` is a thing which can convert those objects into HTTP2 protocol/format. This requires us to read some HTTP2 specs.
- `Model` is a thing which works with resources or transfers data to a consumer/subscriber.

**Comment by Dmitry404** [comment]
Closing since we have a plan
